name: podcast workflow
on: [push]
jobs:
  build:
      runs-on: ubntu-latest
      steps:
        - name: Checkout 
          uses: actions/checkout@v5.0.0
        - name: setup python
          uses: actions/setup-python@v4
          with:
           python-version: '3.10'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pyyaml
        - name:  Run feeder
          run: python feed.py
          
        - name: Push repo
          run: |
             git config user.name github-actions
             git config user.email github-actions@github.com
             git add .
             git commit -m "Modified feed"
             git push
             
             
        
          
          
          

