name: podcast workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name : Run Feed generator
        uses: bindu987654321/podcast-generator@main

      
